export const ROOM_CREATION = 'ROOM_CREATION';
export const ROOM_TITLE = 'ROOM_TITLE';
export const POSTIT_CREATION = 'POSTIT_CREATION';
export const POSTIT_LOCATION = 'POSTIT_LOCATION';
export const POSTIT_VALUE = 'POSTIT_VALUE';
export const POSTIT_DELETION = 'POSTIT_DELETION';
